package com.inautix;
import static springfox.documentation.builders.PathSelectors.regex;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;





@Configuration
@EnableSwagger2

@ComponentScan("com.inautix.HotelService")
public class Swaggerdoc {
	
	@Bean
	public Docket documenation(){
		return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any()).paths(regex("/.*"))
		.build().apiInfo(metadata());
	}

	private ApiInfo metadata(){
		return new ApiInfoBuilder().title("Room Booking").
				description("Swagger documentation has been generated by the open-source Java library [SpringFox](http://springfox.github.io/springfox/)")
				.version("v2")
				.license("BNY Mellon | Terms Of Use")
				.licenseUrl("https://www.bnymellon.com/us/en/terms-of-use.jsp")
				.termsOfServiceUrl("https://www.bnymellon.com/us/en/terms-of-use.jsp").build();
		
	}
	
}
